#!/bin/bash
cd ~/llama.cpp
./build/bin/llama-cli -m ./smollm2-135m-q4_k_m.gguf -p "$*" -n 100 --temp 0.7 --threads 2 --batch-size 512 --ubatch-size 512 --ctx-size 256 --no-mmap --no-display-prompt 2>/dev/null | tail -4
